spring.application.name=sistemaprincipal
spring.mongodb.uri=mongodb+srv://cientistadias_db_user:<senha>@madeira.xkydx8a.mongodb.net/?appName=madeira 
spring.mongodb.database=madeira
api.security.token.secret=minha_chave_secreta_muito_forte_12345